### ISSUE TITLE
graphical improvements

### ISSUE THREAD

**Issue by pbignardi** [pbignardi/snake-js#11]
Nice visual improvements:
- [ ] head of the snake
- [x] Block pattern where the snake is moving
- [ ] Apple for the food
- [x] Gradient for snake body
- [x] arrow to represents the identification map of the selected topology

**Comment by MaxGhi8** [comment]
Other visual improvements:
- [] arrow to represents the identification map of the selected topology

**Comment by MaxGhi8** [comment]
I think that the other two improvements are not feasible for the surface div.
