### ISSUE TITLE
initial screen for starting the game

### ISSUE THREAD

**Issue by pbignardi** [pbignardi/snake-js#2]
initial starting screen of the game. Should allow to select a scale of the game to have more "resolution"

**Comment by pbignardi** [comment]
This could be improved by creating the initial screen with p5, since it allows to create buttons and other fields.
Moreover, this way there is no way to pass stuff around with `sessionStorage`.

**Comment by MaxGhi8** [comment]
Implement in issue 24 without using p5 but only HTML and bootstrap. I take particular care to sessionStorage and localStorage.
